### ISSUE TITLE
ServiceException: Code: notAllowed

### ISSUE THREAD

**Issue by MrFabouMR** [rubit0/MsGraphForUnity#3]
Hey rubit0!
I pulled your files, started it in Unity 2019.4.15f1 and used your OneDriveExample.

When I signed it and search for something it gives me the notAllowed Error.

Greetings!

**Comment by rubit0** [comment]
Did you setup the required API permissions?

**Comment by MrFabouMR** [comment]
I think so, I hope you can work with these screenshots.

https://gyazo.com/ad91942842f7f94bee332aa9be4f2e16
https://gyazo.com/673703d96f91b45ca7b36c5be4e82552
https://gyazo.com/666549314e79f3e7df390f8720778449

**Comment by MrFabouMR** [comment]
Used an Account with Permissions in OneDrive, thanks for your help :-)
